matrix:
  include:
    #- os: linux
    #  dist: bionic
    #  language: cpp
    #  compiler: gcc
    #  addons:
    #    apt:
    #      sources:
    #        - ubuntu-toolchain-r-test
    #      packages:
    #        - g++-8
    #  env: CXX=g++-8 CC=gcc-8
    - os: osx
      osx_image: xcode12.2
      language: cpp
      compiler: clang
      addons:
        homebrew:
          packages:
            - ninja
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew

      before_cache:
        - brew cleanup
    #- os: windows
    #  language: bash
    #  env: CXX=cl.exe
install:
  - |
    if [[ $TRAVIS_OS_NAME == 'windows' ]]; then
      choco install ninja cmake
    elif [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      pipenv global 3.6
      pip install --user ninja cmake
    fi
script:
  - |
    if [[ $TRAVIS_OS_NAME == 'windows' ]]; then
      tools/build.bat
    else
      sh tools/build.sh
    fi
  - ./build/test/tests
